# Generated by Django 5.2 on 2025-04-11 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wiki_the_forest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='usuarios/'),
        ),
    ]
