# Generated by Django 5.2 on 2025-04-14 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wiki_the_forest', '0002_alter_usuario_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='correo',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nombre_usuario',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
